---
env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  prettier/prettier: error
