name: "Build & Test"

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install NPM Packages
        run: |
          npm ci
      - name: Run Build
        run: |
          npm run build
      # - name: Run Linter
      #   run: |
      #     npm run lint
      - name: Run Pack
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm run pack

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Start Test
        uses: PasseiDireto/pd-teams-notification-action@main
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Deployment Started
          notification-color: 17a2b8
      - name: Warning Test
        uses: PasseiDireto/pd-teams-notification-action@main
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Warning! Something Not Quite Right
          notification-color: ffc107
      - name: Error Test
        uses: PasseiDireto/pd-teams-notification-action@main
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: OMG!! Something Exploded
          notification-color: dc3545
      - name: Success Test
        uses: PasseiDireto/pd-teams-notification-action@main
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ vars.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Whew! Everything is right with the world again!
          notification-color: 28a745
      # - uses: ./
      #   with:
      #     github-token: ${{ github.token }}
      #     ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      #     notification-summary: "Emojify! &#x1F6A2​​ &#x2705;"
      #     notification-color: 28a745
